blueprints/health/__init__.py
from blueprints.health.views import health_blueprint

blueprints/health/views.py
from flask import Blueprint, render_template, request
from flask import Response, json
from flask import jsonify

health_blueprint = Blueprint('health', __name__, template_folder='templates')

@health_blueprint.route('/health-report')
def check_health():
    return render_template('health/report_health.html')

@health_blueprint.route('/health', methods=["GET"])
def get_health():
    jd = {'status': 'OK'}
    data = json.dumps(jd)
    resp = Response(data, status=200, mimetype='application/json')
    return resp



@health_blueprint.route("/get_ip", methods=["GET"])
def get_my_ip():
    return jsonify({'ip': request.remote_addr}), 200

blueprints/page/__init__.py
from blueprints.page.views import page_blueprint

blueprints/page/views.py
from flask import Blueprint, render_template
from flask import current_app as app
import sys

page_blueprint = Blueprint('page', __name__, template_folder='templates')

@page_blueprint.route('/')
def home():

    msg = sys.version
    return render_template('page/home.html', msg=msg)

@page_blueprint.route('/terms')
def terms():
    return render_template('page/terms.html')


@page_blueprint.route('/privacy')
def privacy():
    return render_template('page/privacy.html')

blueprints/track/__init__.py
from blueprints.track.views import track_blueprint

blueprints/track/views.py
from flask import Blueprint, render_template, request

track_blueprint = Blueprint('track', __name__, template_folder='templates')

@track_blueprint.route('/track',methods = ['GET'])
def track_form():
    return render_template('track/track.html')

@track_blueprint.route('/result',methods = ['POST'])
def result():
  if request.method == 'POST':
    result = request.form
  return render_template("track/result.html",result = result)

templates/index.html
<!DOCTYPE html>
<html>
<head>
  <title>PyBase</title>
  <style>
    html, body {
      font-family: sans-serif;
      background: #f0f0f0;
      margin: 4em;
    }

    .main {
      background: white;
      border: solid 1px #c0c0c0;
      border-radius: 8px;
      padding: 2em;
    }
  </style>
</head>
<body>

  <section class="main">
    <h1>SITE TESTING RECORDER v0.1</h1>
    <p>This is a Python Flask application foundation.</p>
    <p>Python installed on this server is {{ msg }} </p>
    <p>Application Name is  {{ app_info['app_name'] }} </p>
    <p>Application Version is  {{ app_info['app_version'] }} </p>


  </section>

</body>
</html>

templates/layouts/app.html
{% extends 'layouts/base.html' %}

{% block header %}
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="{{ url_for('page.home') }}">
          <img src="{{ url_for('static', filename='images/bf.jpg') }}"
               class="img-responsive"
               width="229" height="50" title="bf" alt="bf"/>
        </a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          {% if a == 'admin' %}
            <li>
              {% include 'admin/_menu.html' %}
            </li>
          {% endif %}
          {% if a %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle"
                 data-toggle="dropdown"
                 role="button" aria-haspopup="true"
                 aria-expanded="false">Account
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="">Settings</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Session</li>
                <li><a href="">Log out</a></li>
              </ul>
            </li>
          {% else %}
		    <li><a href="{{ url_for('track.track_form') }}">Track</a></li>
            <li><a href="">Log in</a></li>
            <li><a href="">Sign up</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block footer %}
  <li><a href="">Contact</a></li>
  <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
  <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
{% endblock %}

templates/layouts/base.html
{% import 'macros/flash.html' as flash with context %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"content="{% block meta_description %}{% endblock %}">
    <meta name="csrf-token" content="">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/main.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">
    <script src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>
  </head>
  <body>
    {% block header %}{% endblock %}
    
    <main class="container">
      {{ flash.render() }}

      <div class="md-margin-top">{% block heading %}{% endblock %}</div>
      {% block body %}{% endblock %}
    </main>

    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">BF &copy; 2020</li>
          {% block footer %}{% endblock %}
        </ul>
      </div>
    </footer>

    <script
      src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>
    <script
      src="{{ url_for('static', filename='scripts/vendor/moment.min.js') }}">
    </script>
    <script
      src="{{ url_for('static', filename='scripts/main.js') }}">
    </script>
  </body>
</html>

templates/layouts/login.html
{% extends 'layouts/base.html' %}

{% block header %}
  <a href="{{ url_for('page.home') }}">
    <img src="{{ url_for('static', filename='images/bf-large.jpg') }}"
         class="img-responsive center-block md-margin-bottom"
         width="178" height="176" title="BF" alt="BF"/>
  </a>
{% endblock %}

{% block footer %}
  <li><a href="">Sign up today</a></li>
{% endblock %}

templates/macros/flash.html
{# Render Flask messages. #}
{%- macro render() -%}
  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      <div id="flash-messages" class="row sm-margin-top">
        {% for category, msg in messages %}
          <div class="alert alert-{{ category }}" role="alert">
            {{ msg }}
          </div>
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
{%- endmacro -%}

templates/macros/form.html
{# Render a form field's label with visual aid to see if it's required. #}
{%- macro field_label(f) -%}
  <label for="{{ f.id }}">
    {%- if f.flags.required -%}
      <strong>{{ f.label.text }}</strong>
    {%- else %}
      {{ f.label.text }}
    {%- endif %}
  </label>
{%- endmacro -%}


{# Render a form field's errors. #}
{%- macro field_errors(f) -%}
  {% if f.errors %}
    <ul class="list-unstyled text-danger field-error">
      {% for error in f.errors %}
        <li>{{ error | e }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{%- endmacro -%}


{# Render a form field. #}
{%- macro field(f, css_class='form-control') -%}
  {{ f(class=css_class, **kwargs) }}
{%- endmacro -%}


{# Render a checkbox field. #}
{%- macro checkbox_field(f) -%}
  {{ f(type='checkbox', **kwargs) }} {{ f.label }}
{%- endmacro -%}


{# Render a form group with errors for various field types. #}
{%- macro form_group(f, css_class='') -%}
  {% if f.errors %}
    {% set css_class = css_class + ' has-error ' + kwargs.pop('class', '') %}
  {% endif %}

  {% if f.type == 'BooleanField' %}
    <div class="checkbox {{ css_class }}">
    {{ checkbox_field(f, **kwargs) }}
  {% else %}
    <div class="form-group {{ css_class }}">
    {{ field_label(f) }}
    {{ field(f, **kwargs) }}
  {% endif %}

    {{ field_errors(f) }}
    {{ caller () }}
  </div>
{%- endmacro %}


{# Render a form tag that contains a CSRF token and all hidden fields. #}
{%- macro form_tag(endpoint, fid='', css_class='', method='post') -%}
  <form action="{{ url_for(endpoint, **kwargs) }}" method="{{ method }}"
        id="{{ fid }}" class="{{ css_class }}" role="form">
    {{ form.hidden_tag() }}
    {{ caller () }}
  </form>
{%- endmacro -%}


{# Render a form for searching. #}
{%- macro search(endpoint) -%}
  {% call form_tag(endpoint, method='get') %}
    <label for="q"></label>
    <div class="input-group md-margin-bottom">
      <input type="text" class="form-control"
             id="q" name="q" value="{{ request.args.get('q', '') }}"
             placeholder="Search by typing, then press enter...">
    <span class="input-group-addon">
      <i class="fa fa-fw fa-search"></i>
    </span>
    </div>
  {% endcall %}
{%- endmacro -%}

templates/macros/items.html
{# Toggle sorting order on a specific field. #}
{% macro sort(field, title_header=None) -%}
  {% set sort = request.args.get('sort', None) %}
  {% set direction = request.args.get('direction', 'asc') %}
  {% set q = request.args.get('q', '') %}

  {% if title_header == None %}
    {% set label = field | title %}
  {% else %}
    {% set label = title_header %}
  {% endif %}

  {% if sort == field and direction == 'asc' %}
    {% set direction = 'desc' %}
  {% else %}
    {% set direction = 'asc' %}
  {% endif %}

  {% if sort == field %}
    {% set css = direction %}
  {% else %}
    {% set css = 'sort' %}
  {% endif %}

  <a class="{{ css }}" href="{{ url_for(request.endpoint,
                                        q=q,
                                        sort=field,
                                        direction=direction,
                                        **request.view_args) }}">{{ label }}</a>
{%- endmacro %}


{# Paginate through a resource. #}
{% macro paginate(resource) -%}
  {% set args = request.args.to_dict() %}

  <ul class="pagination">
    <li class="{{ 'disabled' if resource.page == 1 }}">
      <a href="{{ url_for(request.endpoint, page=1, **args) }}"
          aria-label="First">
        &laquo; First
      </a>
    </li>
    <li class="{{ 'disabled' if not resource.has_prev }}">
      <a href="{{ url_for(request.endpoint, page=resource.page - 1, **args) }}"
          aria-label="Previous">
        Prev
      </a>
    </li>
  {%- for page in resource.iter_pages() %}
    <li class="{{ 'active' if page and page == resource.page }}">
      {% if page %}
        {% if page != resource.page %}
          <a href="{{ url_for(request.endpoint, page=page, **args) }}">{{ page }}</a>
        {% else %}
          <span class="text-muted">{{ page }}</span>
        {% endif %}
      {% else %}
        <span class="ellipsis">…</span>
      {% endif %}
    </li>
  {%- endfor %}
    <li class="{{ 'disabled' if not resource.has_next }}">
      <a href="{{ url_for(request.endpoint, page=resource.page + 1, **args) }}"
          aria-label="Next">
        Next
      </a>
    </li>
    <li class="{{ 'disabled' if resource.page == resource.pages }}">
      <a href="{{ url_for(request.endpoint, page=resource.pages, **args) }}"
          aria-label="Last">
        Last &raquo;
      </a>
    </li>
  </ul>
{%- endmacro %}